# Generated by Django 5.1.4 on 2025-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_process_payment_status_process_payment_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='dispute_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='dispute_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
